### ISSUE TITLE
Request and Response wrapper class not found

### ISSUE THREAD

**Issue by neXus1987** [quarkiverse/quarkiverse-cxf#68]
hi all,

i got following error when using request/response wrapper:
2020-12-02 21:48:52,634 WARN  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-1) wrapper class not found : de.test.UserRequestWrapper

Maybe classloading under QuarkusCxfProcessor has to be tuned for Request/Response wrapper classes:
wrapperClass = Class.forName(fullClassName);
to
wrapperClass = Thread.currentThread().getContextClassLoader().loadClass(fullClassName);

thanks

**Comment by dufoli** [comment]
fixed on main repo. I have to always use yandex and not class.ForName to check class.

**Comment by dufoli** [comment]
can you check with master branch ?

**Comment by neXus1987** [comment]
ok the Wrapper is now found but i got following exception for the return pojo class (de.dummy.OrderResponse):

```

2020-12-03 11:25:07,322 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.cxf.deployment.QuarkusCxfProcessor#build threw an exception: java.lang.IllegalArgumentException: Must be a Class or String, got de.dummy.OrderResponse
	at io.quarkus.gizmo.DescriptorUtils.objectToDescriptor(DescriptorUtils.java:145)
	at io.quarkus.gizmo.MethodDescriptor.ofMethod(MethodDescriptor.java:83)
	at io.quarkiverse.cxf.deployment.QuarkusCxfProcessor.build(QuarkusCxfProcessor.java:1218)
```

**Comment by neXus1987** [comment]
i guess in QuarkusCxfProcessor on line 1220/1224:

f.type().name() 
to 
f.type().name().toString()

**Comment by dufoli** [comment]
exaclty. I have done so upper but forget the toString() because argument is object....

**Comment by neXus1987** [comment]
works, also in native 👍 
Thanks!
