### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by jimbogithub** [quarkiverse/quarkiverse-cxf#82]
I'm seeing several deployment issues.  I have a system that is running OK in Quarkus Dev mode but fails as an uber-jar in Docker.  I've made some progress getting further:

1. The WebService implementation is not in the uber-jar.  Adding `@Unremovable` resolves this, however would it make sense to include them automatically if they are annotated `@WebService`?  I note that you are currently not looking for this annotation  and requiring `quarkus.cxf.endpoint."xxx".implementor=SomeClass` instead.

2. Following error occurs:

    `ERROR [io.quarkus.runtime.Application] 'main' Failed to start application (with profile dev): org.apache.cxf.BusException: No binding factory for namespace http://schemas.xmlsoap.org/wsdl/soap/ registered.
        at org.apache.cxf.bus.managers.BindingFactoryManagerImpl.getBindingFactory(BindingFactoryManagerImpl.java:93)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:348)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.createBindingInfo(JaxWsServerFactoryBean.java:182)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpointInfo(AbstractWSDLBasedEndpointFactory.java:268)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:146)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
        at io.quarkiverse.cxf.transport.CxfHandler.<init>(CxfHandler.java:122)
        at io.quarkiverse.cxf.CXFRecorder.initServer(CXFRecorder.java:142)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute-1341485114.deploy_0(QuarkusCxfProcessor$startRoute-1341485114.zig:305)
        at io.quarkus.deployment.steps.QuarkusCxfProcessor$startRoute-1341485114.deploy(QuarkusCxfProcessor$startRoute-1341485114.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:729)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
    `
    
    I think there are several `META-INF/cxf/*.txt` files that need to be copied to the uber-jar.  We have the same issue with our home-grown solution.

**Comment by jimbogithub** [comment]
Dug a bit deeper.  This is because we are using `quarkus.package.uber-jar=true` and is the same underlying problem as https://cxf.apache.org/docs/bundling-cxf-into-single-jar-with-maven-shade-plugin.html

Quarkus would need https://github.com/quarkusio/quarkus/issues/5677 to resolve properly.

Workaround is to not use the uber-jar or create your own pre-shaded cxf bundle.

**Comment by jimbogithub** [comment]
Item '1' remains a possible area for improvement.

**Comment by dufoli** [comment]
item 1 is indeed handle in #52

**Comment by jimbogithub** [comment]
Thanks.
