### ISSUE TITLE
NullPointerException upgrading from 0.2 to 0.3

### ISSUE THREAD

**Issue by mauro-antonaci** [quarkiverse/quarkiverse-cxf#93]
My application exposes a quarkus REST service that is also a client of an external CXF service, using quarkiverse-cxf extension. The application itself does not expose any CXF service, it only need to act as a client. Since I upgraded from v. 0.2 to v. 0.3 I receive a NullPointerException in response to any resource requested (even those unrelated to CXF calls, e.g. index.html).

Stacktrace:
`java.lang.NullPointerException
	at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:249)
	at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:193)
	at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:38)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

The WS call was working fine in v. 0.2. In both cases quarkus version is 1.10.5.Final and JDK version is AdoptOpenJdk 11.

To exclude external interferences I reproduced the problem in a minimal application (quarkus getting-started + a simple @WebService annotated interface, with no implementor and no registration as a client: the only presence of a @WebService annotated interface seems to cause the problem).

`
package org.acme;

import javax.jws.WebMethod;
import javax.jws.WebService;

@WebService
public interface ProvaWs {
    @WebMethod
    public String doSomething();
}
`

Note: in v.0.3 it seems that quarkus, at startup, tries to instantiate a web service endpoint even if there is no endpoint registered in application.properties (maybe because it finds a @WebServce annotated interfaces by introspection?):

`
2021-01-08 09:11:39,701 INFO  [org.apa.cxf.wsd.ser.fac.ReflectionServiceFactoryBean] (build-5) Creating Service {http://acme.org/}ProvaWsService from class org.acme.ProvaWs
2021-01-08 09:11:39,731 WARN  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-5) capture generation of org.acme.jaxws_asm.package-info
2021-01-08 09:11:39,734 WARN  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-5) capture generation of org.acme.jaxws_asm.DoSomething
2021-01-08 09:11:39,739 WARN  [io.qua.cxf.dep.QuarkusCxfProcessor] (build-5) capture generation of org.acme.jaxws_asm.DoSomethingResponse
2021-01-08 09:11:39,963 WARN  [io.qua.cxf.CXFRecorder] (Quarkus Main Thread) recorder CXFClientInfoSupplier
2021-01-08 09:11:39,964 WARN  [io.qua.cxf.CXFServletInfos] (Quarkus Main Thread) new CXFServletInfos
2021-01-08 09:11:39,964 INFO  [io.qua.cxf.CXFRecorder] (Quarkus Main Thread) init server
2021-01-08 09:11:39,965 INFO  [io.qua.cxf.tra.CxfHandler] (Quarkus Main Thread) CxfHandler created
2021-01-08 09:11:39,966 WARN  [io.qua.cxf.tra.CxfHandler] (Quarkus Main Thread) no info transmit to servlet
`

**Comment by dufoli** [comment]
hmm I have to remove creation of route if cxfWebService.getImplementor() is empty... It will fix that.

**Comment by mauro-antonaci** [comment]
> 
> 
> hmm I have to remove creation of route if cxfWebService.getImplementor() is empty... It will fix that.

I also think so. I found a workaround to apply in the meantime: if I define and register a dummy implementor of the web service interface, the problem disappear and it works.
